### ISSUE TITLE
Issues handling parentheses

### ISSUE THREAD

**Issue by colinodell** [niklongstone/regex-reverse#8]
I've encountered a few instances where the library doesn't seem to handle `()` characters properly:

| # | Pattern | Expected | Actual |
|----|-----------|--------------|-----------|
| 1 | `((hello world))` | `hello world` | `(hello world)` |
| 2 | `(a(ir|ero))plane` | `airplane` or `aeroplane` | `a(ir|ero)plane` |
| 3 | `([)(])` | `(` or `)` | `[]` |
| 4 | `([)])` | `)` | `[])` |

**Comment by niklongstone** [comment]
Thanks for reporting the issue.

The round brakets feature has actually a bug, below comments to all the patterns value:
About the #1, #3 and #4 are a bug, and I also know why.
The #2 has the unsupported conditional '|'. I will raise an issue for add that feature.

I will add all those patterns to the unit test, and the bug could be fixed in the next release.

**Comment by niklongstone** [comment]
fixed in [tag/0.1.1](https://github.com/niklongstone/regex-reverse/releases/tag/0.1.1)

**Comment by colinodell** [comment]
:) :+1:
